services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: test
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  redis:
    image: "redis:6.2.4"
    command: redis-server
    ports:
      - 6379:6379