services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
  redis:
    image: redis:6.2.4
    container_name: redis
    command: redis-server
    ports:
      - 6379:6379
  grafana:
    ports:
      - 3000:3000
    volumes:
      - "./grafana_data:/var/lib/grafana"
    links:
      - prometheus
    image: grafana/grafana
    container_name: grafana
  prometheus:
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    image: prom/prometheus
    container_name: prometheus
  zipkin:
    ports:
      - 9411:9411
    image: openzipkin/zipkin
    container_name: zipkin